
import { Club, Session, SkillLevel, SessionType } from './types';

export const CLUBS: Club[] = [
  { id: 1, name: 'City Pickleballers', logo: 'https://picsum.photos/seed/club1/100/100' },
  { id: 2, name: 'Suburban Paddles', logo: 'https://picsum.photos/seed/club2/100/100' },
  { id: 3, name: 'Downtown Dinkers', logo: 'https://picsum.photos/seed/club3/100/100' },
];

const getFutureDate = (days: number): string => {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date.toISOString().split('T')[0];
};

export const MOCK_SESSIONS: Session[] = [
  {
    id: 1,
    name: 'Morning Pickleball Social',
    club: CLUBS[0],
    date: getFutureDate(1),
    time: '09:00',
    duration: 120,
    location: 'Central Park Courts',
    description: 'A friendly social game to start your day. All are welcome to join and have fun. We will have multiple courts running.',
    participants: { current: 5, max: 16 },
    price: 5,
    type: SessionType.Social,
    skillLevel: SkillLevel.All,
    host: 'John Doe',
    privacy: 'Public',
  },
  {
    id: 2,
    name: 'Intermediate Drills & Training',
    club: CLUBS[1],
    date: getFutureDate(2),
    time: '18:00',
    duration: 90,
    location: 'Westside Community Center',
    description: 'Focus on improving your dinks, volleys, and third shot drops with a certified coach. Limited spots available.',
    participants: { current: 3, max: 8 },
    price: 20,
    type: SessionType.Training,
    skillLevel: SkillLevel.Intermediate,
    host: 'Coach Alice',
    privacy: 'Public',
  },
  {
    id: 3,
    name: 'Advanced Competitive Play',
    club: CLUBS[2],
    date: getFutureDate(3),
    time: '19:00',
    duration: 150,
    location: 'South Metro Sports Complex',
    description: 'High-level competitive matches for advanced players (4.0+). Bring your A-game!',
    participants: { current: 7, max: 8 },
    price: 15,
    type: SessionType.Competition,
    skillLevel: SkillLevel.Advanced,
    host: 'Admin',
    privacy: 'Public',
  },
  {
    id: 4,
    name: 'Beginner Round Robin',
    club: CLUBS[0],
    date: getFutureDate(4),
    time: '14:00',
    duration: 120,
    location: 'Central Park Courts',
    description: 'A fun and relaxed round robin tournament for beginners. A great way to meet new players and play different people.',
    participants: { current: 10, max: 20 },
    price: 10,
    type: SessionType.RoundRobin,
    skillLevel: SkillLevel.Beginner,
    host: 'Jane Smith',
    privacy: 'Public',
  },
    {
    id: 5,
    name: 'All Levels Afternoon Mixer',
    club: CLUBS[1],
    date: getFutureDate(1),
    time: '15:00',
    duration: 180,
    location: 'Lakeside Courts',
    description: 'Join us for a fun afternoon of pickleball! We\'ll mix and match players of all skill levels for some great games.',
    participants: { current: 12, max: 24 },
    price: 0,
    type: SessionType.Social,
    skillLevel: SkillLevel.All,
    host: 'Suburban Paddles Club',
    privacy: 'Public',
  },
  {
    id: 6,
    name: 'Private Training Session',
    club: CLUBS[2],
    date: getFutureDate(5),
    time: '11:00',
    duration: 60,
    location: 'Private Court (Address on RSVP)',
    description: 'Invite-only training session for members of the Downtown Dinkers club. Please RSVP to receive location details.',
    participants: { current: 1, max: 4 },
    price: 50,
    type: SessionType.Training,
    skillLevel: SkillLevel.Intermediate,
    host: 'Coach Mike',
    privacy: 'Private',
  },
];
